### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by yuanhang-dev** [pmyteh/RISJbot#2]
from .aws_credentials import *
i run the command scrapy crawl yahoo but it gave me this error

ModuleNotFoundError: No module named 'RISJbot.aws_credentials'

my system is Windows 10 
python == 3.7

**Comment by pmyteh** [comment]
Thanks for this - it didn't handle the non-AWS usecase well. I've added some code to check for this and fall back to local storage. Do check your settings.py to make sure that things are set up right for you.
